/**
 * Renders audit results for the terminal and as a Markdown report.
 * @module
 */

import type { AuditResult, DistinguishabilityResult, PairResult, TokenResult } from './evaluate.ts';

const STATUS_ICON: Readonly<Record<string, string>> = {
    pass: 'PASS',
    fail: 'FAIL',
    missing: 'MISSING',
    ok: 'ok',
    warn: 'WARN',
};

/**
 * Produces the Markdown report written to `docs/contrast-report.md`.
 * @param result Audit outcome.
 * @param generatedAt Timestamp for the header.
 * @returns Markdown text.
 */
export function renderMarkdown(result: AuditResult, generatedAt: Date): string {
    const summary = result.failures === 0 ? 'All checks pass.' : `${String(result.failures)} failing check(s).`;
    return [
        '# Contrast report',
        '',
        `Generated by \`pnpm audit:contrast\` on ${generatedAt.toISOString()}. ${summary}`,
        '',
        'Text pairs require 4.5:1, UI boundaries and icons 3:1, dimmed items 3:1 (project policy).',
        'Ratios are never rounded up.',
        '',
        '## Workbench pairs',
        '',
        '| Status | Description | Kind | Foreground | Background | Ratio | Required | Level |',
        '| --- | --- | --- | --- | --- | --- | --- | --- |',
        ...result.pairs.map(renderPairRow),
        '',
        '## Syntax token foregrounds on `editor.background`',
        '',
        '| Status | Rule | Foreground | Ratio | Required |',
        '| --- | --- | --- | --- | --- |',
        ...result.tokens.map(renderTokenRow),
        '',
        '## Distinguishability (informational)',
        '',
        'Closest pair inside each semantic group, per vision type. Delta E (CIE76) below 10 is flagged.',
        '',
        '| Status | Group | Vision | Closest pair | Delta E |',
        '| --- | --- | --- | --- | --- |',
        ...result.groups.map(renderGroupRow),
        '',
    ].join('\n');
}

/**
 * Produces the terminal summary: failures in full, then totals.
 * @param result Audit outcome.
 * @returns Lines to print.
 */
export function renderConsole(result: AuditResult): readonly string[] {
    const failingPairs = result.pairs.filter((pair) => pair.status !== 'pass');
    const failingTokens = result.tokens.filter((token) => token.status === 'fail');
    const warnings = result.groups.filter((group) => group.status === 'warn');
    return [
        ...failingPairs.map(
            (item) =>
                `${STATUS_ICON[item.status] ?? ''} ${item.pair.description}: ${item.pair.foreground} ${item.foregroundHex ?? '?'} on ${item.pair.background} ${item.backgroundHex ?? '?'} = ${item.ratio.toFixed(2)}:1 (needs ${String(item.required)}:1)`,
        ),
        ...failingTokens.map(
            (item) =>
                `FAIL token[${String(item.index)}] ${item.scope}: ${item.foregroundHex} = ${item.ratio.toFixed(2)}:1 (needs ${String(item.required)}:1)`,
        ),
        ...warnings.map(
            (item) =>
                `WARN ${item.group} under ${item.vision}: ${item.closestPair[0]} vs ${item.closestPair[1]} delta E ${item.deltaE.toFixed(1)}`,
        ),
        `pairs: ${String(result.pairs.length - failingPairs.length)}/${String(result.pairs.length)} pass, tokens: ${String(result.tokens.length - failingTokens.length)}/${String(result.tokens.length)} pass, distinguishability warnings: ${String(warnings.length)}`,
    ];
}

function renderPairRow(item: PairResult): string {
    return `| ${STATUS_ICON[item.status] ?? ''} | ${item.pair.description} | ${item.pair.kind} | \`${item.pair.foreground}\` ${item.foregroundHex ?? ''} | \`${item.pair.background}\` ${item.backgroundHex ?? ''} | ${item.ratio.toFixed(2)} | ${String(item.required)} | ${item.level} |`;
}

function renderTokenRow(item: TokenResult): string {
    return `| ${STATUS_ICON[item.status] ?? ''} | ${item.scope} | ${item.foregroundHex} | ${item.ratio.toFixed(2)} | ${String(item.required)} |`;
}

function renderGroupRow(item: DistinguishabilityResult): string {
    return `| ${STATUS_ICON[item.status] ?? ''} | ${item.group} | ${item.vision} | \`${item.closestPair[0]}\` vs \`${item.closestPair[1]}\` | ${item.deltaE.toFixed(1)} |`;
}
