/**
 * Renders audit results for the terminal and as a Markdown report.
 * @module
 */

import type { AuditResult, DistinguishabilityResult, OverlayResult, PairResult, TokenResult } from './evaluate.ts';

const STATUS_ICON: Readonly<Record<string, string>> = {
    pass: 'PASS',
    fail: 'FAIL',
    missing: 'MISSING',
    ok: 'ok',
    warn: 'WARN',
};

/**
 * Produces the Markdown report written to `docs/contrast-report.md`.
 * @param result Audit outcome.
 * @returns Markdown text.
 */
export function renderMarkdown(result: AuditResult): string {
    const summary = result.failures === 0 ? 'All checks pass.' : `${String(result.failures)} failing check(s).`;
    return [
        '# Contrast report',
        '',
        `Generated by \`pnpm audit:contrast\`. ${summary}`,
        '',
        'Text requires 7:1 and may not exceed 14:1; UI boundaries, icons and dimmed items require 4.5:1 and may',
        'not exceed 15.5:1 (14:1 when dimmed); passive marks stay between 4.5:1 and 7:1. Ratios are never rounded.',
        '',
        '## Workbench pairs',
        '',
        '| Status | Description | Kind | Foreground | Background | Ratio | Required | Maximum | Level |',
        '| --- | --- | --- | --- | --- | --- | --- | --- | --- |',
        ...result.pairs.map(renderPairRow),
        '',
        '## Syntax token foregrounds on `editor.background`',
        '',
        '| Status | Rule | Foreground | Ratio | Required | Maximum |',
        '| --- | --- | --- | --- | --- | --- |',
        ...result.tokens.map(renderTokenRow),
        '',
        '## Syntax tokens on overlays behind editor text',
        '',
        'Dimmest token or `editor.foreground` on each overlay stack, composited onto `editor.background`.',
        '',
        '| Status | Overlay | Layers | Composited | Dimmest foreground | Ratio | Required |',
        '| --- | --- | --- | --- | --- | --- | --- |',
        ...result.overlays.map(renderOverlayRow),
        '',
        '## Distinguishability (informational)',
        '',
        'Closest pair inside each semantic group, per vision type. Delta E (CIE76) below 10 is flagged.',
        '',
        '| Status | Group | Vision | Closest pair | Delta E |',
        '| --- | --- | --- | --- | --- |',
        ...result.groups.map(renderGroupRow),
        '',
    ].join('\n');
}

/**
 * Produces the terminal summary: failures in full, then totals.
 * @param result Audit outcome.
 * @returns Lines to print.
 */
export function renderConsole(result: AuditResult): readonly string[] {
    const failingPairs = result.pairs.filter((pair) => pair.status !== 'pass');
    const failingTokens = result.tokens.filter((token) => token.status === 'fail');
    const failingOverlays = result.overlays.filter((overlay) => overlay.status !== 'pass');
    const warnings = result.groups.filter((group) => group.status === 'warn');
    return [
        ...failingPairs.map(
            (item) =>
                `${STATUS_ICON[item.status] ?? ''} ${item.pair.description}: ${item.pair.foreground} ${item.foregroundHex ?? '?'} on ${item.pair.background} ${item.backgroundHex ?? '?'} = ${item.ratio.toFixed(2)}:1 (band ${String(item.required)}:1 to ${String(item.maximum)}:1)`,
        ),
        ...failingTokens.map(
            (item) =>
                `FAIL token[${String(item.index)}] ${item.scope}: ${item.foregroundHex} = ${item.ratio.toFixed(2)}:1 (band ${String(item.required)}:1 to ${String(item.maximum)}:1)`,
        ),
        ...failingOverlays.map(
            (item) =>
                `${STATUS_ICON[item.status] ?? ''} overlay ${item.overlay.description}: ${item.worstForegroundHex ?? '?'} on ${item.backgroundHex ?? '?'} = ${item.ratio.toFixed(2)}:1 (floor ${String(item.required)}:1)`,
        ),
        ...warnings.map(
            (item) =>
                `WARN ${item.group} under ${item.vision}: ${item.closestPair[0]} vs ${item.closestPair[1]} delta E ${item.deltaE.toFixed(1)}`,
        ),
        `pairs: ${String(result.pairs.length - failingPairs.length)}/${String(result.pairs.length)} pass, tokens: ${String(result.tokens.length - failingTokens.length)}/${String(result.tokens.length)} pass, overlays: ${String(result.overlays.length - failingOverlays.length)}/${String(result.overlays.length)} pass, distinguishability warnings: ${String(warnings.length)}`,
    ];
}

function renderPairRow(item: PairResult): string {
    return `| ${STATUS_ICON[item.status] ?? ''} | ${item.pair.description} | ${item.pair.kind} | \`${item.pair.foreground}\` ${item.foregroundHex ?? ''} | \`${item.pair.background}\` ${item.backgroundHex ?? ''} | ${item.ratio.toFixed(2)} | ${String(item.required)} | ${String(item.maximum)} | ${item.level} |`;
}

function renderTokenRow(item: TokenResult): string {
    return `| ${STATUS_ICON[item.status] ?? ''} | ${item.scope} | ${item.foregroundHex} | ${item.ratio.toFixed(2)} | ${String(item.required)} | ${String(item.maximum)} |`;
}

function renderOverlayRow(item: OverlayResult): string {
    const layers = item.overlay.layers.map((layer) => `\`${layer}\``).join(' + ');
    return `| ${STATUS_ICON[item.status] ?? ''} | ${item.overlay.description} | ${layers} | ${item.backgroundHex ?? ''} | ${item.worstForegroundHex ?? ''} | ${item.ratio.toFixed(2)} | ${String(item.required)} |`;
}

function renderGroupRow(item: DistinguishabilityResult): string {
    return `| ${STATUS_ICON[item.status] ?? ''} | ${item.group} | ${item.vision} | \`${item.closestPair[0]}\` vs \`${item.closestPair[1]}\` | ${item.deltaE.toFixed(1)} |`;
}
