/**
 * One-off importer that converts the `dark-2026` seed theme (JSONC) into the
 * TypeScript theme source under `src/` and documents disabled color keys.
 *
 * Usage: `node scripts/import-theme.ts [path/to/seed.json]`
 * @module
 */

import { readFileSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import type { HexColor, TokenColorRule } from '../src/types.ts';
import { extractCommentedEntries, parseJsonc, type CommentedEntry } from './jsonc.ts';

interface SeedTheme {
  readonly type: string;
  readonly colors: Readonly<Record<string, HexColor>>;
  readonly tokenColors: readonly TokenColorRule[];
}

const ROOT = resolve(import.meta.dirname, '..');
const DEFAULT_SEED = resolve(ROOT, 'docs/dark-2026.json');
const GENERATED_HEADER = `// Generated by scripts/import-theme.ts from the dark-2026 seed theme.
// Edit freely: this file is the source of truth from now on.`;

/**
 * Runs the import and writes `src/workbench-colors.ts`, `src/token-colors.ts`
 * and `docs/unassigned-color-keys.md`.
 * @param seedPath Path to the JSONC seed theme.
 */
export function importTheme(seedPath: string): void {
  const raw = readFileSync(seedPath, 'utf8');
  const seed = parseJsonc<SeedTheme>(raw);
  const commented = extractCommentedEntries(raw);

  writeFileSync(resolve(ROOT, 'src/workbench-colors.ts'), renderWorkbenchColors(seed.colors));
  writeFileSync(resolve(ROOT, 'src/token-colors.ts'), renderTokenColors(seed.tokenColors));
  writeFileSync(resolve(ROOT, 'docs/unassigned-color-keys.md'), renderUnassigned(commented));

  console.log(`workbench colors: ${String(Object.keys(seed.colors).length)}`);
  console.log(`token color rules: ${String(seed.tokenColors.length)}`);
  console.log(`commented-out entries: ${String(commented.length)}`);
}

function renderWorkbenchColors(colors: Readonly<Record<string, HexColor>>): string {
  const sortedKeys = Object.keys(colors).sort((a, b) => a.localeCompare(b));
  const lines = sortedKeys.map((key) => `  ${JSON.stringify(key)}: ${JSON.stringify(colors[key])},`);
  return `${GENERATED_HEADER}
import type { WorkbenchColors } from './types.ts';

/** Workbench color assignments for the Ally Dark theme. */
export const workbenchColors = {
${lines.join('\n')}
} as const satisfies WorkbenchColors;
`;
}

function renderTokenColors(rules: readonly TokenColorRule[]): string {
  const body = JSON.stringify(rules, null, 2).replace(/"([A-Za-z_$][\w$]*)":/g, '$1:');
  return `${GENERATED_HEADER}
import type { TokenColorRule } from './types.ts';

/** TextMate token color rules for the Ally Dark theme. */
export const tokenColors: readonly TokenColorRule[] = ${body};
`;
}

function renderUnassigned(entries: readonly CommentedEntry[]): string {
  const rows = entries.map((entry) => `| \`${entry.key}\` | \`${entry.value}\` |`);
  return `# Unassigned workbench color keys

These ${String(entries.length)} keys were present but commented out in the \`dark-2026\` seed theme.
They are not part of the generated theme, so VS Code applies its own defaults for them.
Keep this list as the backlog for future theme coverage work.

| Key | Seed value |
| --- | --- |
${rows.join('\n')}
`;
}

importTheme(process.argv[2] ?? DEFAULT_SEED);
