/**
 * Importer that converts a seed theme captured with VS Code's
 * "Generate Color Theme From Current Settings" (JSONC) into the TypeScript
 * theme source under `src/`. Commented-out entries are the defaults VS Code
 * would apply, so they are promoted to active colors unless `--active-only`
 * is given, in which case they are documented as unassigned keys.
 *
 * Usage: `node scripts/import-theme.ts [path/to/seed.json] [--active-only]`
 * @module
 */

import { readFileSync, rmSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import type { HexColor, TokenColorRule } from '../src/types.ts';
import { isHexColor } from './color/hex.ts';
import { extractCommentedEntries, parseJsonc, type CommentedEntry } from './jsonc.ts';

interface SeedTheme {
    readonly type: string;
    readonly colors: Readonly<Record<string, HexColor>>;
    readonly tokenColors: readonly TokenColorRule[];
}

const ROOT = resolve(import.meta.dirname, '..');
const DEFAULT_SEED = resolve(ROOT, 'docs/dark-high-contrast.json');
const UNASSIGNED_PATH = resolve(ROOT, 'docs/unassigned-color-keys.md');
const GENERATED_HEADER = `// Generated by scripts/import-theme.ts from the dark-high-contrast seed theme.
// Edit freely: this file is the source of truth from now on.`;

/**
 * Runs the import and writes `src/workbench-colors.ts` and `src/token-colors.ts`.
 * With `activeOnly` the commented-out entries are listed in
 * `docs/unassigned-color-keys.md` instead of being promoted.
 * @param seedPath Path to the JSONC seed theme.
 * @param activeOnly Whether to skip promoting commented-out entries.
 */
export function importTheme(seedPath: string, activeOnly: boolean): void {
    const raw = readFileSync(seedPath, 'utf8');
    const seed = parseJsonc(raw) as SeedTheme;
    const commented = extractCommentedEntries(raw);
    const colors = activeOnly ? seed.colors : promoteCommented(seed.colors, commented);

    writeFileSync(resolve(ROOT, 'src/workbench-colors.ts'), renderWorkbenchColors(colors));
    writeFileSync(resolve(ROOT, 'src/token-colors.ts'), renderTokenColors(seed.tokenColors));
    writeUnassigned(activeOnly ? commented : []);

    console.log(
        `workbench colors: ${String(Object.keys(colors).length)} (${String(Object.keys(seed.colors).length)} active in seed)`,
    );
    console.log(`token color rules: ${String(seed.tokenColors.length)}`);
    console.log(`commented-out entries: ${String(commented.length)} ${activeOnly ? 'documented' : 'promoted'}`);
}

function promoteCommented(
    active: Readonly<Record<string, HexColor>>,
    commented: readonly CommentedEntry[],
): Readonly<Record<string, HexColor>> {
    const promoted = Object.fromEntries(
        commented.filter((entry) => isHexColor(entry.value)).map((entry) => [entry.key, entry.value as HexColor]),
    );
    return { ...promoted, ...active };
}

function writeUnassigned(entries: readonly CommentedEntry[]): void {
    if (entries.length === 0) {
        rmSync(UNASSIGNED_PATH, { force: true });
        return;
    }
    writeFileSync(UNASSIGNED_PATH, renderUnassigned(entries));
}

function renderWorkbenchColors(colors: Readonly<Record<string, HexColor>>): string {
    const sortedKeys = Object.keys(colors).sort((a, b) => a.localeCompare(b));
    const lines = sortedKeys.map((key) => `    ${JSON.stringify(key)}: ${JSON.stringify(colors[key])},`);
    return `${GENERATED_HEADER}
import type { WorkbenchColors } from './types.ts';

/** Workbench color assignments for the Ally Dark theme. */
export const workbenchColors = {
${lines.join('\n')}
} as const satisfies WorkbenchColors;
`;
}

function renderTokenColors(rules: readonly TokenColorRule[]): string {
    const supported = rules.map((rule) => ({ ...rule, settings: withoutBackground(rule.settings) }));
    const body = JSON.stringify(supported, null, 4).replace(/"([A-Za-z_$][\w$]*)":/g, '$1:');
    return `${GENERATED_HEADER}
import type { TokenColorRule } from './types.ts';

/** TextMate token color rules for the Ally Dark theme. */
export const tokenColors: readonly TokenColorRule[] = ${body};
`;
}

function withoutBackground(settings: TokenColorRule['settings']): TokenColorRule['settings'] {
    const supported = Object.entries(settings).filter(([key]) => key !== 'background');
    return Object.fromEntries(supported);
}

function renderUnassigned(entries: readonly CommentedEntry[]): string {
    const rows = entries.map((entry) => `| \`${entry.key}\` | \`${entry.value}\` |`);
    return `# Unassigned workbench color keys

These ${String(entries.length)} keys were present but commented out in the seed theme.
They are not part of the generated theme, so VS Code applies its own defaults for them.
Keep this list as the backlog for future theme coverage work.

| Key | Seed value |
| --- | --- |
${rows.join('\n')}
`;
}

const positional = process.argv.slice(2).filter((argument) => !argument.startsWith('--'));
importTheme(positional[0] ?? DEFAULT_SEED, process.argv.includes('--active-only'));
