// Generated by scripts/import-theme.ts from the dark-high-contrast seed theme.
// Edit freely: this file is the source of truth from now on.
import { text } from './palette.ts';
import type { TokenColorRule } from './types.ts';

/** TextMate token color rules for the A11y Matrix Dark theme. */
export const tokenColors: readonly TokenColorRule[] = [
    {
        scope: [
            'meta.embedded',
            'source.groovy.embedded',
            'string meta.image.inline.markdown',
            'variable.legacy.builtin.python',
        ],
        settings: {
            foreground: text.primary,
        },
    },
    {
        scope: 'emphasis',
        settings: {
            fontStyle: 'italic',
        },
    },
    {
        scope: 'strong',
        settings: {
            fontStyle: 'bold',
        },
    },
    {
        scope: 'meta.diff.header',
        settings: {
            foreground: '#9595ff',
        },
    },
    {
        scope: 'comment',
        settings: {
            foreground: '#83ab70',
        },
    },
    {
        scope: 'constant.language',
        settings: {
            foreground: '#66a6da',
        },
    },
    {
        scope: [
            'constant.numeric',
            'constant.other.color.rgb-value',
            'constant.other.rgb-value',
            'support.constant.color',
        ],
        settings: {
            foreground: '#B5CEA8',
        },
    },
    {
        scope: 'constant.regexp',
        settings: {
            foreground: '#c88fb1',
        },
    },
    {
        scope: 'constant.character',
        settings: {
            foreground: '#66a6da',
        },
    },
    {
        scope: 'entity.name.tag',
        settings: {
            foreground: '#66a6da',
        },
    },
    {
        scope: ['entity.name.tag.css', 'entity.name.tag.less'],
        settings: {
            foreground: '#D7BA7D',
        },
    },
    {
        scope: 'entity.other.attribute-name',
        settings: {
            foreground: '#9adbfe',
        },
    },
    {
        scope: [
            'entity.other.attribute-name.class.css',
            'source.css entity.other.attribute-name.class',
            'entity.other.attribute-name.id.css',
            'entity.other.attribute-name.parent-selector.css',
            'entity.other.attribute-name.parent.less',
            'source.css entity.other.attribute-name.pseudo-class',
            'entity.other.attribute-name.pseudo-element.css',
            'source.css.less entity.other.attribute-name.id',
            'entity.other.attribute-name.scss',
        ],
        settings: {
            foreground: '#D7BA7D',
        },
    },
    {
        scope: 'invalid',
        settings: {
            foreground: '#f77a7a',
        },
    },
    {
        scope: 'markup.underline',
        settings: {
            fontStyle: 'underline',
        },
    },
    {
        scope: 'markup.bold',
        settings: {
            fontStyle: 'bold',
        },
    },
    {
        scope: 'markup.heading',
        settings: {
            foreground: '#76a1e9',
            fontStyle: 'bold',
        },
    },
    {
        scope: 'markup.italic',
        settings: {
            fontStyle: 'italic',
        },
    },
    {
        scope: 'markup.strikethrough',
        settings: {
            fontStyle: 'strikethrough',
        },
    },
    {
        scope: 'markup.inserted',
        settings: {
            foreground: '#B5CEA8',
        },
    },
    {
        scope: 'markup.deleted',
        settings: {
            foreground: '#ce9279',
        },
    },
    {
        scope: 'markup.changed',
        settings: {
            foreground: '#66a6da',
        },
    },
    {
        scope: ['punctuation.definition.tag'],
        settings: {
            foreground: '#a0a0a0',
        },
    },
    {
        scope: 'meta.preprocessor',
        settings: {
            foreground: '#66a6da',
        },
    },
    {
        scope: 'meta.preprocessor.string',
        settings: {
            foreground: '#ce9279',
        },
    },
    {
        scope: 'meta.preprocessor.numeric',
        settings: {
            foreground: '#B5CEA8',
        },
    },
    {
        scope: 'meta.structure.dictionary.key.python',
        settings: {
            foreground: '#9adbfe',
        },
    },
    {
        scope: 'storage',
        settings: {
            foreground: '#66a6da',
        },
    },
    {
        scope: 'storage.type',
        settings: {
            foreground: '#66a6da',
        },
    },
    {
        scope: 'storage.modifier',
        settings: {
            foreground: '#66a6da',
        },
    },
    {
        scope: 'string',
        settings: {
            foreground: '#ce9279',
        },
    },
    {
        scope: 'string.tag',
        settings: {
            foreground: '#ce9279',
        },
    },
    {
        scope: 'string.value',
        settings: {
            foreground: '#ce9279',
        },
    },
    {
        scope: 'string.regexp',
        settings: {
            foreground: '#dc8a8a',
        },
    },
    {
        scope: [
            'punctuation.definition.template-expression.begin',
            'punctuation.definition.template-expression.end',
            'punctuation.section.embedded',
        ],
        settings: {
            foreground: '#66a6da',
        },
    },
    {
        scope: ['meta.template.expression'],
        settings: {
            foreground: text.primary,
        },
    },
    {
        scope: [
            'support.type.vendored.property-name',
            'support.type.property-name',
            'source.css variable',
            'source.coffee.embedded',
        ],
        settings: {
            foreground: text.primary,
        },
    },
    {
        scope: 'keyword',
        settings: {
            foreground: '#66a6da',
        },
    },
    {
        scope: 'keyword.control',
        settings: {
            foreground: '#66a6da',
        },
    },
    {
        scope: 'keyword.operator',
        settings: {
            foreground: text.primary,
        },
    },
    {
        scope: [
            'keyword.operator.new',
            'keyword.operator.expression',
            'keyword.operator.cast',
            'keyword.operator.sizeof',
            'keyword.operator.logical.python',
        ],
        settings: {
            foreground: '#66a6da',
        },
    },
    {
        scope: 'keyword.other.unit',
        settings: {
            foreground: '#B5CEA8',
        },
    },
    {
        scope: 'support.function.git-rebase',
        settings: {
            foreground: text.primary,
        },
    },
    {
        scope: 'constant.sha.git-rebase',
        settings: {
            foreground: '#B5CEA8',
        },
    },
    {
        scope: ['storage.modifier.import.java', 'variable.language.wildcard.java', 'storage.modifier.package.java'],
        settings: {
            foreground: text.primary,
        },
    },
    {
        scope: 'variable.language.this',
        settings: {
            foreground: '#66a6da',
        },
    },
    {
        scope: [
            'entity.name.function',
            'support.function',
            'support.constant.handlebars',
            'source.powershell variable.other.member',
        ],
        settings: {
            foreground: '#d6d69d',
        },
    },
    {
        scope: [
            'support.class',
            'support.type',
            'entity.name.type',
            'entity.name.namespace',
            'entity.name.scope-resolution',
            'entity.name.class',
            'storage.type.cs',
            'storage.type.generic.cs',
            'storage.type.modifier.cs',
            'storage.type.variable.cs',
            'storage.type.annotation.java',
            'storage.type.generic.java',
            'storage.type.java',
            'storage.type.object.array.java',
            'storage.type.primitive.array.java',
            'storage.type.primitive.java',
            'storage.type.token.java',
            'storage.type.groovy',
            'storage.type.annotation.groovy',
            'storage.type.parameters.groovy',
            'storage.type.generic.groovy',
            'storage.type.object.array.groovy',
            'storage.type.primitive.array.groovy',
            'storage.type.primitive.groovy',
        ],
        settings: {
            foreground: '#4EC9B0',
        },
    },
    {
        scope: [
            'meta.type.cast.expr',
            'meta.type.new.expr',
            'support.constant.math',
            'support.constant.dom',
            'support.constant.json',
            'entity.other.inherited-class',
            'punctuation.separator.namespace.ruby',
        ],
        settings: {
            foreground: '#4EC9B0',
        },
    },
    {
        scope: [
            'keyword.control',
            'source.cpp keyword.operator.new',
            'source.cpp keyword.operator.delete',
            'keyword.other.using',
            'keyword.other.directive.using',
            'keyword.other.operator',
        ],
        settings: {
            foreground: '#c88dc3',
        },
    },
    {
        scope: ['variable', 'meta.definition.variable.name', 'support.variable'],
        settings: {
            foreground: '#9adbfe',
        },
    },
    {
        scope: ['meta.object-literal.key'],
        settings: {
            foreground: '#9adbfe',
        },
    },
    {
        scope: [
            'support.constant.property-value',
            'support.constant.font-name',
            'support.constant.media-type',
            'support.constant.media',
            'constant.other.color.rgb-value',
            'constant.other.rgb-value',
            'support.constant.color',
        ],
        settings: {
            foreground: '#ce9279',
        },
    },
    {
        scope: 'meta.resultLinePrefix.contextLinePrefix.search',
        settings: {
            foreground: '#a7e1a7',
        },
    },
    {
        scope: 'token.info-token',
        settings: {
            foreground: '#76a1e9',
        },
    },
    {
        scope: 'token.warn-token',
        settings: {
            foreground: '#00ba00',
        },
    },
    {
        scope: 'token.error-token',
        settings: {
            foreground: '#ff7474',
        },
    },
    {
        scope: 'token.debug-token',
        settings: {
            foreground: '#c388eb',
        },
    },
];
